### ISSUE TITLE
Is it double visual representation that is taking effect or multi layer feature?

### ISSUE THREAD

**Issue by whitesockcat** [HJYao00/DenseConnector#4]
Interesting Job!
Quick question:
As i know, double the channels or tokens will leads to high performance.
Do you have any ablation study about this?

Sorry if this is a silly question, I haven't read the article thoroughly yet.

**Comment by HJYao00** [comment]
Thank you for your interest in our work! Detailed ablation studies can be found in Tables 1 and 5. 
For the Sparse Token Integration method, which involves increasing the token dimension, the performance of using three or four layers of features is quite similar, with four layers being slightly better. For the Sparse Channel Integration method, three layers of features generally perform better than two or four layers.
