### ISSUE TITLE
the question of repository installation

### ISSUE THREAD

**Issue by darkpromise98** [HJYao00/DenseConnector#5]
A nice work for VLM!

When I try to install the repository by the  `pip install -e .`, I suffer a error:
`ERROR: file:///home/user/DenseConnector does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
`

It seems that the repository not have a `pyproject.toml` like [LLaVA repository](https://github.com/haotian-liu/LLaVA)

**Comment by HJYao00** [comment]
We apologize for any inconvenience. We have now uploaded the pyproject.toml file. Additionally, if you wish to fine-tune the llama3 model, you may need to update some packages (https://github.com/huggingface/blog/blob/main/llama3.md), such as upgrading transformers to version 4.40.0.
