### ISSUE TITLE
Many thanks for your excellent work!

### ISSUE THREAD

**Issue by YuchenLiu98** [HJYao00/DenseConnector#6]
Many thanks for your excellent work!
COMM (which has already been on Arxiv on 2023.10 https://arxiv.org/pdf/2310.08825.pdf) already proposed to merge the features of CLIP and DINOv2 to realize MLLM, maybe this paper should cite this reference.

**Comment by HJYao00** [comment]
Thank you for your interest in our work and for your detailed attention. I would like to mention that we have already cited the COMM in our paper. 
![WechatIMG46](https://github.com/HJYao00/DenseConnector/assets/119796101/ac67a0ac-82ee-42f7-b19a-1ca4a88b913e)

**Comment by YuchenLiu98** [comment]
Sorry for the misleading.
