### ISSUE TITLE
Question on feature selection

### ISSUE THREAD

**Issue by gheinrich** [HJYao00/DenseConnector#7]
Hello, thank you very much for a very nice paper and for sharing your code!

In table 1 in the paper, you are showing ablations on visual layer selection, and what seems to work best for you in CLIP case is to concatenate the averages of layers `(1-12)` and `(13-24)`. I see in your code that in addition to this, you concatenate the image features:

```
   ...
    elif mm_dense_connector_type == 'dci':
        image_features_dc = dense_connector_dci(image_features, image_forward_outs, is_siglip)
        image_features = torch.cat((image_features, image_features_dc), dim=-1)
```

Thus I was wondering if in the ablations and other experimental results in the paper, the `image_features` are always used, or if this was a recent addition in your code?

Thank you!

**Comment by HJYao00** [comment]
Thank you for your interest in our work! As stated in our paper, image_features are always used in the DCI.
![image](https://github.com/HJYao00/DenseConnector/assets/119796101/bc10a03f-f9dd-4495-8572-1392612621d6)

**Comment by gheinrich** [comment]
Thank you!
