### ISSUE TITLE
code

### ISSUE THREAD

**Issue by DavidYanAnDe** [HJYao00/DenseConnector#8]
what's wrong with your code in builder.py for `    def forward(self, image_forward_outs, selected_features):
        return x
`

**Comment by HJYao00** [comment]
I apologize for the inconvenience caused by this code. The code is redundant, and I have removed it. I will close this issue. If you have any other questions, please reopen it.

**Comment by HJYao00** [comment]
I apologize for the inconvenience caused by this code. The code is redundant, and I have removed it.
